class FeatureAltera:
    def __init__(self):
        self.option_name = "Altera"
        self.option_content = self.content()
        self.order = 13

    def content(self):
        return """
<!DOCTYPE html>
<html lang="en">
  <body style="margin:0; padding:20px; font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif; background:#f9fafb; color:#1f2937; line-height:1.6;">

    <!-- Title -->
    <h1 style="color:#1d4ed8; font-size:28px; font-weight:700; margin-bottom:8px;">Altera Flow</h1>

    <!-- Overview -->
    <p style="font-size:15px; color:#4b5563; margin-bottom:20px;">
      The <strong>Altera flow</strong> integrates <strong>Quartus Prime</strong> for synthesis, place-and-route,
      static timing analysis (STA), and on-chip debug (SignalTap). Simulation can be performed with
      <strong>ModelSim</strong>, <strong>Questa</strong>, or <strong>Xcelium</strong>.
    </p>

    <!-- Quick Info -->
    <div style="background:#eff6ff; border-left:5px solid #2563eb; padding:14px; border-radius:6px; margin-bottom:20px;">
      <h2 style="font-size:18px; font-weight:700; color:#1e40af; margin-bottom:6px;">Environment</h2>
      <ul style="margin:0; padding-left:20px; font-size:14px;">
        <li><strong>Vendor:</strong> Altera (Intel)</li>
        <li><strong>Tool:</strong> Quartus Prime</li>
        <li><strong>Simulator:</strong> ModelSim / Questa / Xcelium</li>
        <li><strong>Linter:</strong> Verilator</li>
      </ul>
    </div>

    <!-- Requirements -->
    <div style="background:#ffffff; border:1px solid #d1d5db; border-radius:6px; padding:14px; margin-bottom:20px;">
      <h2 style="font-size:18px; font-weight:700; color:#1d4ed8; margin-bottom:6px;">Requirements</h2>
      <ul style="margin:0; padding-left:20px; font-size:14px;">
        <li>Quartus must be installed and available in <code>$PATH</code>.</li>
        <li>The <strong>constraints</strong> folder must include:
          <ul>
            <li><code>&lt;module_name&gt;.sdc</code> – primary timing constraints.</li>
            <li><code>&lt;module_name&gt;.pin</code> – pin information, used to configure the QSF file.</li>
            <li><code>&lt;module_name&gt;.altera_cnfg</code> – additional QSF settings (e.g., voltages, memory configs).</li>
          </ul>
        </li>
        <li>Optional files:
          <ul>
            <li><code>&lt;module_name&gt;.stp</code> – enables SignalTap logic analyzer flow during synthesis.</li>
            <li><code>&lt;module_name&gt;.partition</code> – pre-synthesized or pre-routed partitions for faster P&amp;R.</li>
          </ul>
        </li>
      </ul>
    </div>

    <!-- Flow -->
    <div style="background:#fff7ed; border-left:5px solid #d97706; border-radius:6px; padding:14px; margin-bottom:20px;">
      <h2 style="font-size:18px; font-weight:700; color:#92400e; margin-bottom:6px;">Flow</h2>
      <p style="font-size:14px;">To run the Altera flow, configure your project YAML file with <code>vendor: altera</code>, then populate the manifests:</p>
      <ol style="font-size:14px; margin-left:20px;">
        <li>Add RTL files to <code>manifest_rtl</code>.</li>
        <li>Add testbench files to <code>manifest_tb</code>. If <code>.c</code> files are required for DPI, list them in the <code>software</code> manifest.<br>
            (<em>DPI is supported, but VPI is not</em>.)</li>
        <li>Add IPs to the <code>ip</code> manifest:
          <ul>
            <li>IPs must be provided as <code>.ip</code> or <code>.qsys</code> files.</li>
            <li>They are automatically generated by Platform Designer or IP Catalog.</li>
          </ul>
        </li>
      </ol>

      <p style="margin-top:12px; font-size:14px;"><strong>Command sequence:</strong></p>
      <pre style="background:#f3f4f6; padding:10px; border-radius:6px; font-size:13px; overflow:auto;">
rls create
rls lint
rls sim
rls synth
rls route
rls sta
rls bit
      </pre>
    </div>

    <!-- TODO -->
    <div style="background:#fee2e2; border-left:5px solid #dc2626; border-radius:6px; padding:14px; margin-bottom:20px;">
      <h2 style="font-size:18px; font-weight:700; color:#b91c1c; margin-bottom:6px;">TODO / Known Limitations</h2>
      <ul style="font-size:14px; margin-left:20px;">
        <li><strong>Netlist simulation:</strong> Only supported if the user manually generates the netlist and lists it in <code>rtl/tb</code> manifests.</li>
        <li><strong>STA reports:</strong> STA runs, but report fetching/parsing is incomplete.</li>
        <li><strong>Nios II MSS support:</strong> Config files are supported, but integration with firmware flow requires improvement.</li>
        <li><strong>Bitstream generation:</strong> Untested.</li>
        <li><strong>Partial reconfiguration:</strong> Not supported.</li>
      </ul>
    </div>

  </body>
</html>
"""